// Reader-facing, scoped review gates. Remove only after canonical source repair.
export const reviewNotices={
 'kanazawa-medical-2025-general-late-mathematics':{
  'major-question-01':{
   title:'解説の式の区切りと、場合分けを修復待ちです',
   message:'(4)の二次方程式が別々の数式枠へ分断され、途中の項だけが独立した式のように見えます。確率の答えは全216通りの検算と一致していますが、該当導出は元HTMLの修復完了まで編集確認用として扱ってください。',
  },
  'major-question-03':{
   title:'傾きの負号が元HTMLから欠落しています',
   message:'最初に並ぶ2つ目の傾きは、問題・解答原本では負です。元HTMLの問題と解説ではこの負号が抜けています。解説ページの図は原本条件から独立計算したものですが、本文の修復までは第3問を演習・採点の対象外としてください。',
  },
  'major-question-04':{
   title:'問題のベクトル記号と解説の途中式を修復待ちです',
   message:'冒頭で求める関係はG₁G₂とABのベクトルの関係ですが、元HTMLから矢印が抜けています。切断点を求める連立式なども省略されています。図は独立した座標計算に基づきますが、該当設問・導出の正式な教材利用は本文の修復後にしてください。',
  },
 },
 'kanazawa-medical-2025-general-early-physics':{
  'major-question-01':{
   title:'(2)の近似条件と、(3)の記号説明を補足確認中です',
   message:'元解説は、観測周期の補正を一次近似として扱う説明が不足しています。また(3)の速度・半径記号の定義が学習者版で省略されています。図は問題条件から作図しましたが、該当解説は修復待ちの編集確認用としてご覧ください。',
  },
 },
 'kanazawa-medical-2025-general-early-mathematics':{
  'major-question-03':{
   title:'(4)のマーク欄は元HTMLの修復待ちです',
   message:'原本の2桁の解答欄「ワヲ」が、HTMLでは「ワ」だけになっています。解答18の変更ではありません。解答欄の復元までは(4)をマーク式の採点対象外としてください。',
  },
  'major-question-04':{
   title:'交点と接点を区別してご覧ください',
   message:'元解説の見出しは紛らわしい表現ですが、Aは円と放物線の交点であり、2曲線が接しているわけではありません。前半は円の接線、後半は放物線の接線を使います。本文の見出しと補足説明は修復待ちです。',
  },
 },
 'jikei-2025-general-physics':{
  'major-question-01':{
   title:'問3・問4・問5の条件を元HTMLへ復元待ちです',
   message:'問3は原本で求める比とHTMLの式が異なり、問4の微小変化の条件、問5の反証に使う仮定も省略されています。図は原本の意味を確認して作図しましたが、本文修復までは該当設問を演習・採点の対象外としてください。',
  },
  'major-question-02':{
   title:'問3以降の近似条件と説明を補足確認中です',
   message:'元HTMLには、反跳を無視できる極限の条件、光のドップラー効果の近似条件、位置エネルギーの座標の説明が不足しています。問6の記述内容も原本の趣旨と照合済みの修復待ちです。該当箇所は正式な教材として使わず、編集確認用としてご覧ください。',
  },
 },
 'jichi-medical-2025-general-physics':{
  'major-question-14':{
   title:'問題18の力の説明を補足確認中です',
   message:'40 Nと9.0 Nは別々の実験の力です。元解説では、それぞれの接地点まわりのモーメントを使って両実験を結び付ける説明が不足しています。該当する説明を補足確認中です。',
  },
  'major-question-16':{
   title:'問題20の「必要十分条件」の前提を確認中です',
   message:'静かに離した位置Pから滑り始める条件と、動き始めた後にOを通り越す条件は別です。問題文が始動を前提としているかを確認するまで、問題20は演習・採点の対象外としてください。',
  },
 },
 'international-health-welfare-2025-general-physics':{
  'major-question-02':{
   title:'第2問の加速度記号と、つり合いの説明を確認中です',
   message:'冒頭はaを相対加速度としていますが、問2以降はaが床から見たPの加速度、a_rが相対加速度です。図と解説は後者に対応します。また、外力f=TはP・Q・滑車をまとめた系の水平つり合いで考えます。元HTMLの修復までは記号の定義に注意してください。',
  },
  'major-question-04':{
   title:'第4問・問5の選択肢を照合中です',
   message:'ポアソンの法則から得られる式と、選択肢①の指数表記が一致していません。正しい選択肢が元HTMLにないため、原本照合・修復が済むまで問5（解答番号22）は採点対象外としてください。',
  },
 },
 'international-health-welfare-2025-general-mathematics':{
  'major-question-01':{
   title:'第1問(C)・(E)の問題と解答を照合中です',
   message:'対数不等式の定数、双曲線の焦点と接点について、問題HTMLと解答の式が一致していません。原本照合・修復が完了するまで(C)・(E)は演習・採点の対象外としてください。',
  },
  'major-question-02':{
   title:'第2問(2)の解説文を確認中です',
   message:'Mは2本の接線の接点R・Sの中点です。元解説にはQ・Rの中点とする誤記と、四角形ABCDを正方形とする誤記があります。追加した軌跡図は問題の接点中点から計算しています。',
  },
  'major-question-03':{
   title:'第3問(3)(ii)の解答欄を照合中です',
   message:'元問題HTMLに漸化式・一般項が完成した形で記載されています。またp_nはAにいる確率ですが、元解説にはDとする誤記があります。解答欄の復元までは該当設問を採点しないでください。「通る」が辺上の通過を含む点も原本で確認しています。',
  },
  'major-question-04':{
   title:'第4問の符号説明と最終積分を確認中です',
   message:'(2)(ii)の絶対値を外す区間の説明が逆になっており、(3)の積分値と対数の変形にも不整合があります。三角形はx>0の条件から描いていますが、該当解説・最終解答の教材利用は原本照合・修復後にしてください。',
  },
 },
 'hyogo-medical-2025-general-a-b-physics':{
  'major-question-01':{
   title:'問1(4)・(6)・(10)の速度条件は元データを確認中です',
   message:'垂直抗力の式と、解答の速度上限でtan αの次数が一致していません。後続の角度条件も含め、原本照合・修正が完了するまで該当する解答を演習の採点に使用しないでください。',
  },
  'major-question-02':{
   title:'問2の方向選択図は確認中です',
   message:'元HTMLにa・bの矢印と電源極性の対応がありません。図2を確認できるまで、(1)②・④・⑤の方向選択は演習・採点の対象外としてください。',
  },
  'major-question-04':{
   title:'問4(5)の導出過程は確認中です',
   message:'原解説の距離CDの中間式に符号の不一致があり、学習者向けHTMLではその過程が省略されています。焦点への光線を新たに図示していますが、該当導出の教材利用は原本照合・修正後にしてください。',
  },
 },
 'fukuoka-2025-general-keitobetsu-physics':{
  'major-question-01':{
   title:'〔Ⅰ〕(10)の解説は記号を確認中です',
   message:'元解説のうなりの周期の式で、元の音の振動数とうなりの振動数が混同されています。該当式は原本照合・修正が完了するまで正式な教材として使用しないでください。',
  },
  'major-question-03':{
   title:'〔Ⅲ〕(6)の速度の大きさは条件を確認中です',
   message:'問題に記された反発係数の範囲と、解説の速度の「大きさ」の符号に不整合があります。(6)の採点と(7)〜(8)で使う符号の説明は、原本照合・修正が完了するまで確認用として扱ってください。',
  },
 },
 'fujita-health-2025-general-early-physics':{
  'major-question-04':{
   title:'第4問・問9〜10の解説は前提を確認中です',
   message:'元解答は問10を「数式のグラフ」として扱っていますが、この限定が学習者向けHTMLから抜けています。下向きの速度や再衝突を含む物理的な適用範囲は確認中です。以下のグラフも数式の可視化に限り、確認完了まで正式な演習・採点用に使用しないでください。',
  },
 },
 'fujita-health-2025-general-early-mathematics':{
  'major-question-01':{
   title:'第1問の解説は一部確認中です',
   message:'(1)の体積計算、(2)の偏角条件、(8)の置換後の値域について、元データの説明に不整合があります。問題条件・解答値の変更ではありませんが、該当解説は確認完了まで正式な教材として使用しないでください。',
  },
 },
 'dokkyo-medical-2025-general-early-physics':{
  'major-question-04':{
   title:'第4問・問3〜4は元データを確認中です',
   message:'問題文の電流条件「I₀/6」と解説の「I₀」が一致していません。原本と照合するまで、問3〜4は演習・採点の対象外としてください。',
  },
 },
};
/** @type {Record<string, {title: string, message: string}>} */
export const analysisReviewNotices={
 'kanazawa-medical-2025-general-late-mathematics':{
  title:'問題の記号と配点の説明は元HTMLの修復待ちです',
  message:'第3問の負号、第4問のベクトル矢印、解説の途中式を修復待ちです。元分析の配点説明も実データと一致していません。現在は7つの論理小問・仮配点100点の集計を表示しており、目標点を含め編集確認用です。',
 },
 'kanazawa-medical-2025-general-early-physics':{
  title:'近似の説明と分析用語は元HTMLの修復待ちです',
  message:'第1問(2)の一次近似の説明と、分析の「光行差」という用語を修復待ちです。第2問も代入過程の補足を依頼しています。配点・目標点・所要時間は編集上の仮設定として、修復後に再確認します。',
 },
 'kanazawa-medical-2025-general-early-mathematics':{
  title:'解答欄と解説の一部は元HTMLの修復待ちです',
  message:'第3問(4)のマーク欄、第4問の交点・接点の見出しを修復待ちです。第3問(4)は(3)の分散の結果が必要です。分析・目標点は編集上の仮設定として、問題・解説の修復後に再確認します。',
 },
 'jikei-2025-general-physics':{
  title:'問題・解説の一部は元HTMLの修復待ちです',
  message:'求める比、反証の仮定、近似条件などに転記の欠落があります。分析・目標点は編集確認用です。問題と解説を修復した後、難易度・所要時間・解く順番を再確認してください。',
 },
 'international-health-welfare-2025-general-physics':{
  title:'一部の問題表記は元データを照合中です',
  message:'第2問の加速度記号、第4問・問5の選択肢に不整合があります。分析・目標点は編集確認用の暫定表示です。原本修復後に該当設問の評価・選択順序を再確認してください。',
 },
 'international-health-welfare-2025-general-mathematics':{
  title:'分析の前提となる問題・解説を照合中です',
  message:'第1問の対数・双曲線、第2問の点の定義、第3問の確率の定義と解答欄、第4問の積分に元HTMLの不整合があります。以下の分析は元データのレビュー用表示です。目標点や選択順序を学習・出願判断の根拠として使わず、問題の修復後に評価を再確認してください。',
 },
};
const escape=value=>String(value).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');
export function withReviewNotice(html,packageId,majorId){
 const notice=reviewNotices[packageId]?.[majorId];
 if(!notice)return html;
 if(!html.includes('</h2>'))throw Error('Review notice needs a major heading');
 return html.replace('</h2>',`</h2><aside class="past-exam-source-review" role="note" data-source-review="required"><strong>${escape(notice.title)}</strong><p>${escape(notice.message)}</p></aside>`);
}
