import type { UniversityAdmissions } from './universityAdmissions.ts';
import copy from '../data/tottoriReaderCopy.json' with { type: 'json' };
import overview from '../data/tottoriUniversityOverview.json' with { type: 'json' };

const escape=(s:string)=>s.replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&#39;');
const paragraphs=(s:string)=>{const out:string[]=[];let list:string[]=[];const flush=()=>{if(list.length){out.push(`<ul>${list.map(t=>`<li>${escape(t)}</li>`).join('')}</ul>`);list=[];}};for(const line of s.split('\n')){if(line.startsWith('・'))list.push(line.slice(1));else{flush();out.push(`<p>${escape(line)}</p>`);}}flush();return out.join('');};
const sourceHint='<p class="admission-section-links"><a class="admission-source-hint" href="#admission-sources">情報ソースはこちら</a></p>';

export function tottoriAdmissionsMetadata(data:UniversityAdmissions){return{title:'鳥取大学医学部｜2027年度入試情報',displayTitle:'鳥取大学 医学部2027年度入試情報',displayTitleLines:['鳥取大学 医学部','2027年度入試情報'],modified:data.verifiedAt.slice(0,10),description:'鳥取大学医学科の2027年度一般前期・学校推薦型選抜Ⅱ・私費外国人留学生選抜。募集人数、出願・手続期限、科目・配点、出題範囲、地域枠の条件、会場・受験票と2026年度入学者統計を紹介します。',lead:'鳥取大学医学部医学科の2027年度入試について、選抜方式別の日程、会場、科目・配点、出題範囲、地域枠の条件をまとめています。公表済みの試験時間と、募集要項の公開後に更新する項目を分けて掲載しています。出願前には、該当年度の募集要項と大学の変更通知をご確認ください。',keyPoints:['一般前期は一般枠53人・とっとり医療人養成枠7人。地域枠は鳥取県11人・島根県5人の申請後の予定で、個別試験は2027年2月25日・26日です。','一般前期は共通テスト920点＋個別試験700点。第1段階選抜には共通テスト650点以上が必要です。','推薦Ⅱは一般枠15人・地域枠5人、面接は2026年12月5日。地域枠では県の奨学金受給と卒後勤務の確約が必要です。']};}

/** Every restored fact retains a visible destination and its original source/status. */
export function renderTottoriAdmissionsReadable(data:UniversityAdmissions):string{
 if(data.path!=='/information-tottori/'||data.schemes.map(s=>s.id).join(',')!=='general,general-tottori,general-shimane,general-training,recommendation-general,recommendation-region,recommendation-special,private-foreign')throw new Error('Tottori presentation requires the reviewed eight schemes');
 const item=(id:string)=>{const x=copy.items.find(i=>i.id===id);if(!x)throw new Error(`Missing Tottori item ${id}`);return x;};
 const provenance=(origins:string[])=>origins.map(origin=>{if(origin.startsWith('coverage/'))return{origin};const [schemeId,kind,n]=origin.split('/'),scheme=data.schemes.find(s=>s.id===schemeId)!;const row=kind==='note'?scheme.notes[Number(n)]:kind==='schedule'?scheme.scheduleRows[Number(n)]:kind==='exam'?scheme.examRows[Number(n)]:scheme.venueRows[Number(n)];if(!row)throw new Error(`Tottori canonical fact changed: ${origin}`);return{origin,sourceIds:row.sourceIds,...('status' in row?{status:row.status}:{})};});
 const attrs=(id:string)=>`data-tottori-fact="${id}" data-admission-provenance="${escape(JSON.stringify(provenance(item(id).origins)))}"`;
 const fact=(id:string)=>{const x=item(id);return`<div class="admission-fact" ${attrs(id)}><dt>${escape(x.label)}</dt><dd>${paragraphs(x.body)}</dd></div>`;};
 const facts=(where:string)=>`<dl class="admission-facts">${copy.items.filter(i=>i.where===where).map(i=>fact(i.id)).join('')}</dl>`;
 const dates=(where:string,title:string)=>`<table class="admission-dates-table" data-tottori-table="${where}"><caption class="admission-sr-only">${title}</caption><thead><tr><th scope="col">項目</th><th scope="col">日程・条件</th></tr></thead><tbody>${copy.items.filter(i=>i.where===where).map(x=>`<tr ${attrs(x.id)}><th scope="row">${escape(x.label)}</th><td>${paragraphs(x.body)}</td></tr>`).join('')}</tbody></table>`;
 const mobile=(label:string,body:string)=>`<td><span class="admission-mobile-label" aria-hidden="true">${label}</span>${paragraphs(body)}</td>`;
 const rows=[['general','2027年1月25日〜2月3日','2027年2月25日・26日'],['general-tottori','2027年1月25日〜2月3日','2027年2月25日・26日'],['general-shimane','2027年1月25日〜2月3日','2027年2月25日・26日'],['general-training','2027年1月25日〜2月3日','2027年2月25日・26日'],['recommendation-general','2026年11月2日〜9日','面接：2026年12月5日'],['recommendation-region','2026年11月2日〜9日','面接：2026年12月5日'],['recommendation-special','未公表','未公表'],['private-foreign','2027年1月25日〜2月3日','2027年2月25日']];
 const summary=`<h3 id="admission-overview">入試方式・募集人数・主要日程</h3><table class="admission-overview-table" data-tottori-table="overview"><caption class="admission-sr-only">鳥取大学医学科 2027年度入試（出願書類の受付期間）</caption><thead><tr><th scope="col">入試方式</th><th scope="col">募集人数</th><th scope="col">出願書類の受付</th><th scope="col">個別試験</th></tr></thead><tbody>${rows.map(([id,application,trial])=>`<tr ${attrs(`quota-${id}`)}><th scope="row"><a href="#${['general-tottori','general-shimane','general-training'].includes(id)?'admission-general-frame':`admission-scheme-${id}`}">${item(`quota-${id}`).label}</a></th>${mobile('募集人数',item(`quota-${id}`).body)}${mobile('出願書類の受付',application)}${mobile('個別試験',trial)}</tr>`).join('')}</tbody></table><div class="admission-important" ${attrs('capacity-condition')}>${paragraphs(item('capacity-condition').body)}</div>${sourceHint}`;
 const scores=[['国語（必須）','200点','課さない','課さない'],['地歴・公民','100点','課さない','課さない'],['数学','200点','200点','課さない'],['理科','200点','200点','課さない'],['外国語','200点','200点','課さない'],['情報Ⅰ（必須）','20点','課さない','課さない'],['面接','対象外','100点','100点'],['小論文','対象外','課さない','課さない']];
 const scoreTable=`<h3 id="admission-scores">一般前期・推薦Ⅱの科目と配点</h3><table class="admission-score-table" data-tottori-table="scores" ${attrs('scores')}><caption>一般前期4枠・推薦Ⅱの一般枠と地域枠</caption><thead><tr><th scope="col" style="width:25%">教科・試験</th><th scope="col">共通テスト</th><th scope="col">前期個別</th><th scope="col">推薦Ⅱ個別</th></tr></thead><tbody>${scores.map(([name,c,g,r])=>`<tr><th scope="row">${name}</th><td>${c}</td><td>${g}</td><td>${r}</td></tr>`).join('')}<tr class="admission-score-total"><th scope="row">合計</th><td>920点</td><td>700点</td><td>100点</td></tr><tr class="admission-score-total"><th scope="row">総合計</th><td>共通＋個別</td><td>1,620点</td><td>1,020点</td></tr></tbody></table>${facts('common-test')}<h4 class="admission-group-title">共通テストの科目選択・英語換算</h4>${facts('common-subjects')}${sourceHint}`;
 const frames=copy.items.filter(i=>i.where==='general-frame').map(x=>`<h4 class="admission-group-title" id="admission-general-frame">${escape(x.label)}の資格・確約</h4><dl class="admission-facts">${fact(x.id)}</dl>`).join('');
 const ranges=`<h3 id="admission-individual-range">一般前期・私費外国人の出題範囲</h3>${facts('individual-range')}${sourceHint}`;
 const general=`<h3 id="admission-scheme-general">医学科 一般選抜（前期4枠）</h3><h4 class="admission-group-title">出願・試験・入学手続の日程</h4>${dates('general-dates','一般選抜前期4枠の日程と締切条件')}${sourceHint}<h4 class="admission-group-title">出願資格・各枠の条件</h4>${facts('general-qualification')}${frames}${sourceHint}${scoreTable}${ranges}<h4 class="admission-group-title">一般前期の選抜・面接の判定</h4>${facts('general-selection')}${sourceHint}<h4 class="admission-group-title">一般前期の試験会場</h4>${facts('general-venue')}${sourceHint}<h4 class="admission-group-title">一般前期の併願・出願時の注意</h4>${facts('general-notes')}${sourceHint}`;
 const recommendation=`<h3 id="admission-recommendation">医学科 学校推薦型選抜Ⅱ（一般枠・地域枠）</h3><h4 class="admission-group-title">出願・試験・入学手続の日程</h4>${dates('recommendation-dates','推薦Ⅱ一般枠・地域枠の日程と締切条件')}${sourceHint}<h4 class="admission-group-title">両枠の推薦・書類条件</h4>${facts('recommendation-qualification')}<h4 class="admission-group-title" id="admission-scheme-recommendation-general">一般枠の学歴・成績</h4>${facts('recommendation-general-qualification')}<h4 class="admission-group-title" id="admission-scheme-recommendation-region">地域枠の学歴・成績</h4>${facts('recommendation-region-qualification')}${sourceHint}<h4 class="admission-group-title">試験科目・合否判定</h4><p><a href="#admission-scores">共通テストと面接の配点・科目選択</a></p>${facts('recommendation-selection')}${sourceHint}<h4 class="admission-group-title">会場・受験票</h4>${facts('recommendation-venue')}${sourceHint}<h4 class="admission-group-title">併願・推薦人数・辞退</h4>${facts('recommendation-notes')}${sourceHint}<h3 id="admission-regional-career">推薦Ⅱ地域枠の奨学金・卒後勤務</h3>${facts('regional-career')}${sourceHint}`;
 const special=`<h3 id="admission-scheme-recommendation-special">推薦Ⅱ 特別養成枠の公開予定</h3>${facts('special')}${sourceHint}`;
 const foreign=`<h3 id="admission-scheme-private-foreign">医学科 私費外国人留学生選抜</h3><h4 class="admission-group-title">資格確認・出願・試験・手続の日程</h4>${dates('foreign-dates','私費外国人留学生選抜の日程と締切条件')}${sourceHint}<h4 class="admission-group-title">出願資格</h4>${facts('foreign-qualification')}${sourceHint}<h4 class="admission-group-title">試験科目・合否判定</h4><p>個別試験の英語・数学・理科の範囲は、<a href="#admission-individual-range">一般前期と共通の出題範囲</a>をご覧ください。</p>${facts('foreign-selection')}<h4 class="admission-group-title">2月25日の試験時間</h4><table class="admission-dates-table" data-tottori-table="foreign-timetable"><caption class="admission-sr-only">私費外国人留学生選抜の個別試験時間</caption><thead><tr><th scope="col">試験</th><th scope="col">時間</th></tr></thead><tbody>${copy.foreignTimetable.map(([subject,time])=>`<tr><th scope="row">${escape(subject)}</th><td>${escape(time)}</td></tr>`).join('')}</tbody></table>${sourceHint}<h4 class="admission-group-title">会場・受験票</h4>${facts('foreign-venue')}${sourceHint}`;
 const sources=`<details class="admission-source-footer"><summary>情報ソースはこちら</summary><div id="admission-sources"><p>鳥取大学の公式資料（確認日：<time data-university-admissions-verified-at datetime="${escape(data.verifiedAt)}">${data.verifiedAt.slice(0,10)}</time>）</p><ul class="admission-source-list" data-admission-source-list>${data.sources.map(s=>`<li data-admission-source-id="${s.id}"><a href="${escape(s.url)}">${escape(s.title)}</a>${s.pages?`<small>${escape(Array.isArray(s.pages)?`PDF p.${s.pages.join('、')}`:s.pages)}</small>`:''}</li>`).join('')}</ul></div></details>`;
 return`<h2 id="最新の入試情報">2027年度の入試情報</h2><section class="admission-readable tottori-readable" data-admissions-presentation="tottori-readable-v1" data-university-admissions-year="2027">${summary}${general}${recommendation}${special}${foreign}<h3 id="admission-publication">募集要項の公開予定・掲載範囲</h3>${facts('publication')}${sources}</section>`;
}

export function renderTottoriUniversityOverview():string{
 const {address,entrants}=overview;if(entrants.male+entrants.female!==entrants.total)throw new Error('Tottori entrant totals changed');
 return`<h2 id="大学基本情報">大学基本情報</h2><section class="admission-readable tottori-readable" data-tottori-university-overview><h3 id="所在地">所在地</h3><p>${escape(address.campus)}<br>〒${address.postalCode} ${escape(address.street)}</p><h3 id="アクセス">アクセス</h3><ul>${overview.access.map(s=>`<li>${escape(s)}</li>`).join('')}</ul><h3 id="男女比">男女別の入学者</h3><table class="admission-score-table" data-tottori-table="entrants"><caption>2026年度 医学部医学科入学者・105人<br><small>2026年5月1日時点。国費留学生を含む。</small></caption><thead><tr><th scope="col">区分</th><th scope="col">人数</th><th scope="col">割合</th></tr></thead><tbody>${[['男性',entrants.male],['女性',entrants.female]].map(([label,n])=>`<tr><th scope="row">${label}</th><td>${n}人</td><td>${(Number(n)/entrants.total*100).toFixed(1)}％</td></tr>`).join('')}</tbody></table><details class="admission-source-footer"><summary>情報ソースはこちら</summary><ul class="admission-source-list">${overview.sources.map(s=>`<li><a href="${escape(s.url)}">${escape(s.title)}</a>${'pages' in s?`<small>PDF p.${s.pages?.join('、')}（冊子p.25）</small>`:''}</li>`).join('')}</ul><p>確認日：${overview.verifiedAt}</p></details></section>`;
}
