import type { UniversityAdmissions } from './universityAdmissions.ts';
import copy from '../data/yamaguchiReaderCopy.json' with { type: 'json' };
import overview from '../data/yamaguchiUniversityOverview.json' with { type: 'json' };
const escape=(s:string)=>s.replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&#39;');
const paragraphs=(s:string)=>{const out:string[]=[];let list:string[]=[];const flush=()=>{if(list.length){out.push(`<ul>${list.map(t=>`<li>${escape(t)}</li>`).join('')}</ul>`);list=[];}};for(const line of s.split('\n')){if(line.startsWith('・'))list.push(line.slice(1));else{flush();out.push(`<p>${escape(line)}</p>`);}}flush();return out.join('');};
const sourceHint='<p class="admission-section-links"><a class="admission-source-hint" href="#admission-sources">情報ソースはこちら</a></p>';
export function yamaguchiAdmissionsMetadata(data:UniversityAdmissions){return{title:'山口大学医学部｜2027年度入試情報',displayTitle:'山口大学 医学部2027年度入試情報',displayTitleLines:['山口大学 医学部','2027年度入試情報'],modified:data.verifiedAt.slice(0,10),description:'山口大学医学科の2027年度一般選抜。前期53人（定員増承認時55人予定）、後期10人（全国枠7人・地域枠3人以内）。日程、科目・配点、出題範囲、地域枠の条件、所在地・アクセスと2026年度入学者統計を紹介します。',lead:'山口大学医学部医学科の2027年度一般選抜について、日程、会場、科目・配点、出題範囲、地域枠の条件を大学公式資料に基づきまとめています。試験時間や締切条件などの未公表事項は、募集要項の公開後に更新します。出願前には、該当年度の募集要項と大学の変更通知をご確認ください。',keyPoints:['前期は53人、定員増が認められた場合は55人予定。個別試験は2027年2月25日・26日です。','共通テストは全枠950点。個別試験は前期600点、後期500点で、後期は小論文300点と面接200点です。','後期10人のうち全国枠7人・地域枠3人以内。地域枠は卒業後、県内での臨床研修2年間と、その後4年以上の活動の確約が必要です。']};}

/** Common facts have one visible destination and retain each scheme's provenance. */
export function renderYamaguchiAdmissionsReadable(data:UniversityAdmissions):string{
 if(data.path!=='/information-yamaguchi/'||data.schemes.map(s=>s.id).join(',')!=='general-early,general-late-national,general-late-regional')throw new Error('Yamaguchi presentation requires the reviewed three schemes');
 const item=(id:string)=>{const x=copy.items.find(i=>i.id===id);if(!x)throw new Error(`Missing Yamaguchi item ${id}`);return x;};
 const provenance=(origins:string[])=>origins.map(origin=>{if(origin.startsWith('coverage/'))return{origin};const [schemeId,kind,n]=origin.split('/'),scheme=data.schemes.find(s=>s.id===schemeId)!;const row=kind==='note'?scheme.notes[Number(n)]:kind==='schedule'?scheme.scheduleRows[Number(n)]:kind==='exam'?scheme.examRows[Number(n)]:scheme.venueRows[Number(n)];if(!row)throw new Error(`Yamaguchi canonical fact changed: ${origin}`);return{origin,sourceIds:row.sourceIds,...('status' in row?{status:row.status}:{})};});
 const attrs=(id:string)=>`data-yamaguchi-fact="${id}" data-admission-provenance="${escape(JSON.stringify(provenance(item(id).origins)))}"`;
 const fact=(id:string)=>{const x=item(id);return`<div class="admission-fact" ${attrs(id)}><dt>${escape(x.label)}</dt><dd>${paragraphs(x.body)}</dd></div>`;};
 const facts=(where:string)=>`<dl class="admission-facts">${copy.items.filter(i=>i.where===where).map(i=>fact(i.id)).join('')}</dl>`;
 const dates=(where:string,title:string)=>`<table class="admission-dates-table" data-yamaguchi-table="${where}"><caption class="admission-sr-only">${title}</caption><thead><tr><th scope="col">項目</th><th scope="col">日程・条件</th></tr></thead><tbody>${copy.items.filter(i=>i.where===where).map(x=>`<tr ${attrs(x.id)}><th scope="row">${escape(x.label)}</th><td>${paragraphs(x.body)}</td></tr>`).join('')}</tbody></table>`;
 const mobileCell=(label:string,body:string)=>`<td><span class="admission-mobile-label" aria-hidden="true">${label}</span>${paragraphs(body)}</td>`;
 const quotaRows=[['quota-early','admission-scheme-general-early','2027年2月25日・26日'],['quota-national','admission-scheme-general-late-national','2027年3月12日・13日'],['quota-regional','admission-scheme-general-late-regional','2027年3月12日・13日']];
 const summary=`<h3 id="admission-overview">入試方式・募集人数・主要日程</h3><table class="admission-overview-table" data-yamaguchi-table="overview"><caption class="admission-sr-only">山口大学医学科 2027年度一般選抜</caption><thead><tr><th scope="col">入試方式</th><th scope="col">募集人数</th><th scope="col">出願受付</th><th scope="col">個別試験</th></tr></thead><tbody>${quotaRows.map(([id,target,trial])=>`<tr ${attrs(id)}><th scope="row"><a href="#${target}">${item(id).label}</a></th>${mobileCell('募集人数',item(id).body)}${mobileCell('出願受付','2027年1月25日〜2月3日')}${mobileCell('個別試験',trial)}</tr>`).join('')}</tbody></table><div ${attrs('quota-condition')}>${paragraphs(item('quota-condition').body)}</div><p data-yamaguchi-addition="early-vacancy">総合型・学校推薦型選抜の欠員は、前期日程の募集人数に加わります。</p>${sourceHint}`;
 const scores=[['国語','200点','課さない','課さない'],['地歴・公民','100点','課さない','課さない'],['数学','200点','200点','課さない'],['理科','200点','200点','課さない'],['英語','200点','200点','課さない'],['情報Ⅰ','50点','課さない','課さない'],['小論文','対象外','課さない','300点'],['面接','対象外','総合審査の資料','200点']];
 const scoreTable=`<h3 id="admission-scores">教科・試験別の配点</h3><table class="admission-score-table" data-yamaguchi-table="scores" ${attrs('scores')}><caption>共通テスト・前期個別試験・後期個別試験<br><small>後期は全国枠・地域枠に共通</small></caption><thead><tr><th scope="col" style="width:25%">教科・試験</th><th scope="col">共通テスト</th><th scope="col">前期個別</th><th scope="col">後期個別</th></tr></thead><tbody>${scores.map(([name,c,e,l])=>`<tr${name==='国語'?` ${attrs('ct-4')}`:''}><th scope="row">${name}</th><td>${c}</td><td>${e}</td><td>${l}</td></tr>`).join('')}<tr class="admission-score-total"><th scope="row">合計</th><td>950点</td><td>600点</td><td>500点</td></tr><tr class="admission-score-total"><th scope="row">総合計</th><td>共通＋個別</td><td>1,550点</td><td>1,450点</td></tr></tbody></table>${facts('common-exam')}<h4 class="admission-group-title">共通テストの科目選択・換算</h4>${facts('common-subjects')}${sourceHint}`;
 const regional=`<h3 id="admission-scheme-general-late-regional">後期地域枠の出願・卒業後の条件</h3><p>一般選抜の出願資格に加え、出身・居住条件と卒業後の条件の両方を満たす必要があります。</p>${facts('regional')}${sourceHint}`;
 const sources=`<details class="admission-source-footer"><summary>情報ソースはこちら</summary><div id="admission-sources"><p>山口大学の公式資料（確認日：<time data-university-admissions-verified-at datetime="${escape(data.verifiedAt)}">${data.verifiedAt.slice(0,10)}</time>）</p><ul class="admission-source-list" data-admission-source-list>${data.sources.map(s=>`<li data-admission-source-id="${s.id}"><a href="${escape(s.url)}">${escape(s.title)}</a>${s.pages?`<small>${escape(Array.isArray(s.pages)?`PDF p.${s.pages.join('、')}`:s.pages)}</small>`:''}</li>`).join('')}</ul></div></details>`;
 return`<h2 id="最新の入試情報">2027年度の入試情報</h2><section class="admission-readable yamaguchi-readable" data-admissions-presentation="yamaguchi-readable-v1" data-university-admissions-year="2027">${summary}<h3 id="admission-common">全日程共通の出願・受験条件</h3><h4 class="admission-group-title">出願・共通テスト・手続の日程</h4>${dates('common-dates','全日程共通の日程と締切条件')}${sourceHint}<h4 class="admission-group-title">出願資格と事前相談</h4>${facts('common')}${sourceHint}${scoreTable}<h3 id="admission-scheme-general-early">医学科 一般選抜（前期日程）</h3>${dates('early-dates','前期日程の個別試験・合格発表')}<h4 class="admission-group-title">個別試験の出題範囲・選抜条件</h4>${facts('early-exam')}${sourceHint}<h3 id="admission-scheme-general-late-national">医学科 一般選抜（後期全国枠・地域枠共通）</h3>${dates('late-dates','後期全国枠・地域枠共通の個別試験・合格発表')}<h4 class="admission-group-title">個別試験・選抜条件</h4>${facts('late-exam')}${facts('late-note')}${sourceHint}${regional}<h3 id="admission-venue">試験時間・会場・受験票</h3>${facts('venue')}${sourceHint}<h3 id="admission-coverage">募集要項の公開予定・掲載範囲</h3>${facts('coverage')}${sources}</section>`;
}
export function renderYamaguchiUniversityOverview():string{
 const {address,entrants}=overview;if(entrants.male+entrants.female!==entrants.total||entrants.ages.reduce((sum,r)=>sum+Number(r[1]),0)!==entrants.total)throw new Error('Yamaguchi entrant totals changed');
 const table=(id:string,title:string,rows:[string,number][])=>`<h3 id="${id}">${title}</h3><table class="admission-score-table" data-yamaguchi-table="${id}"><caption>2026年度 医学部医学科入学者・109人<br><small>一般選抜と学校推薦型選抜Ⅱの合計</small></caption><thead><tr><th scope="col">区分</th><th scope="col">人数</th><th scope="col">割合</th></tr></thead><tbody>${rows.map(([label,n])=>`<tr><th scope="row">${label}</th><td>${n}人</td><td>${(n/entrants.total*100).toFixed(1)}％</td></tr>`).join('')}</tbody></table>`;
 return`<h2 id="大学基本情報">大学基本情報</h2><section class="admission-readable yamaguchi-readable" data-yamaguchi-university-overview><h3 id="所在地">所在地</h3><p>${address.campus}<br>〒${address.postalCode} ${address.street}</p><h3 id="アクセス">アクセス</h3><ul>${overview.access.map(s=>`<li>${escape(s)}</li>`).join('')}</ul>${table('男女比','男女別の入学者',[['男性',entrants.male],['女性',entrants.female]])}${table('年齢別','年齢別の入学者',entrants.ages as [string,number][])}<p class="admission-value-detail">年齢別の区分です。現役・既卒別の人数は、この統計からは分かりません。</p><details class="admission-source-footer"><summary>情報ソースはこちら</summary><ul class="admission-source-list">${overview.sources.map(s=>`<li><a href="${escape(s.url)}">${escape(s.title)}</a>${s.pages?`<small>PDF p.${s.pages.join('、')}</small>`:''}</li>`).join('')}</ul><p>確認日：${overview.verifiedAt}</p></details></section>`;
}
